# coding: utf-8

"""
    Marketcheck Cars API

    <b>Access the New, Used and Certified cars inventories for all Car Dealers in US.</b> <br/>The data is sourced from online listings by over 44,000 Car dealers in US. At any time, there are about 6.2M searchable listings (about 1.9M unique VINs) for Used & Certified cars and about 6.6M (about 3.9M unique VINs) New Car listings from all over US. We use this API at the back for our website <a href='https://www.marketcheck.com' target='_blank'>www.marketcheck.com</a> and our Android and iOS mobile apps too.<br/><h5> Few useful links : </h5><ul><li>A quick view of the API and the use cases is depicated <a href='https://portals.marketcheck.com/mcapi/' target='_blank'>here</a></li><li>The Postman collection with various usages of the API is shared here https://www.getpostman.com/collections/2752684ff636cdd7bac2</li></ul>  # noqa: E501

    OpenAPI spec version: 1.0.3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from setuptools import setup, find_packages  # noqa: H301

NAME = "marketcheck-api-sdk"
VERSION = "1.0.0"
# To install the library, run the following
#
# python setup.py install
#
# prerequisite: setuptools
# http://pypi.python.org/pypi/setuptools

REQUIRES = ["urllib3 >= 1.15", "six >= 1.10", "certifi", "python-dateutil"]

setup(
    name=NAME,
    version=VERSION,
    description="Marketcheck Cars API",
    author_email="",
    url="",
    keywords=["Swagger", "Marketcheck Cars API"],
    install_requires=REQUIRES,
    packages=find_packages(),
    include_package_data=True,
    long_description="""\
    &lt;b&gt;Access the New, Used and Certified cars inventories for all Car Dealers in US.&lt;/b&gt; &lt;br/&gt;The data is sourced from online listings by over 44,000 Car dealers in US. At any time, there are about 6.2M searchable listings (about 1.9M unique VINs) for Used &amp; Certified cars and about 6.6M (about 3.9M unique VINs) New Car listings from all over US. We use this API at the back for our website &lt;a href&#x3D;&#39;https://www.marketcheck.com&#39; target&#x3D;&#39;_blank&#39;&gt;www.marketcheck.com&lt;/a&gt; and our Android and iOS mobile apps too.&lt;br/&gt;&lt;h5&gt; Few useful links : &lt;/h5&gt;&lt;ul&gt;&lt;li&gt;A quick view of the API and the use cases is depicated &lt;a href&#x3D;&#39;https://portals.marketcheck.com/mcapi/&#39; target&#x3D;&#39;_blank&#39;&gt;here&lt;/a&gt;&lt;/li&gt;&lt;li&gt;The Postman collection with various usages of the API is shared here https://www.getpostman.com/collections/2752684ff636cdd7bac2&lt;/li&gt;&lt;/ul&gt;  # noqa: E501
    """
)
