# coding: utf-8

"""
    Marketcheck Cars API

    <b>Access the New, Used and Certified cars inventories for all Car Dealers in US.</b> <br/>The data is sourced from online listings by over 44,000 Car dealers in US. At any time, there are about 6.2M searchable listings (about 1.9M unique VINs) for Used & Certified cars and about 6.6M (about 3.9M unique VINs) New Car listings from all over US. We use this API at the back for our website <a href='https://www.marketcheck.com' target='_blank'>www.marketcheck.com</a> and our Android and iOS mobile apps too.<br/><h5> Few useful links : </h5><ul><li>A quick view of the API and the use cases is depicated <a href='https://portals.marketcheck.com/mcapi/' target='_blank'>here</a></li><li>The Postman collection with various usages of the API is shared here https://www.getpostman.com/collections/2752684ff636cdd7bac2</li></ul>  # noqa: E501

    OpenAPI spec version: 1.0.3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class CompetitorsSameCars(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'name': 'str',
        'avg_price': 'float',
        'avg_miles': 'float',
        'avg_market_value': 'float'
    }

    attribute_map = {
        'name': 'name',
        'avg_price': 'avg_price',
        'avg_miles': 'avg_miles',
        'avg_market_value': 'avg_market_value'
    }

    def __init__(self, name=None, avg_price=None, avg_miles=None, avg_market_value=None):  # noqa: E501
        """CompetitorsSameCars - a model defined in Swagger"""  # noqa: E501

        self._name = None
        self._avg_price = None
        self._avg_miles = None
        self._avg_market_value = None
        self.discriminator = None

        if name is not None:
            self.name = name
        if avg_price is not None:
            self.avg_price = avg_price
        if avg_miles is not None:
            self.avg_miles = avg_miles
        if avg_market_value is not None:
            self.avg_market_value = avg_market_value

    @property
    def name(self):
        """Gets the name of this CompetitorsSameCars.  # noqa: E501

        ymm_comb_name  # noqa: E501

        :return: The name of this CompetitorsSameCars.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this CompetitorsSameCars.

        ymm_comb_name  # noqa: E501

        :param name: The name of this CompetitorsSameCars.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def avg_price(self):
        """Gets the avg_price of this CompetitorsSameCars.  # noqa: E501

        Price of year make model combination  # noqa: E501

        :return: The avg_price of this CompetitorsSameCars.  # noqa: E501
        :rtype: float
        """
        return self._avg_price

    @avg_price.setter
    def avg_price(self, avg_price):
        """Sets the avg_price of this CompetitorsSameCars.

        Price of year make model combination  # noqa: E501

        :param avg_price: The avg_price of this CompetitorsSameCars.  # noqa: E501
        :type: float
        """

        self._avg_price = avg_price

    @property
    def avg_miles(self):
        """Gets the avg_miles of this CompetitorsSameCars.  # noqa: E501

        Mileage of year make model combination  # noqa: E501

        :return: The avg_miles of this CompetitorsSameCars.  # noqa: E501
        :rtype: float
        """
        return self._avg_miles

    @avg_miles.setter
    def avg_miles(self, avg_miles):
        """Sets the avg_miles of this CompetitorsSameCars.

        Mileage of year make model combination  # noqa: E501

        :param avg_miles: The avg_miles of this CompetitorsSameCars.  # noqa: E501
        :type: float
        """

        self._avg_miles = avg_miles

    @property
    def avg_market_value(self):
        """Gets the avg_market_value of this CompetitorsSameCars.  # noqa: E501

        Estimated market value of year make model combination  # noqa: E501

        :return: The avg_market_value of this CompetitorsSameCars.  # noqa: E501
        :rtype: float
        """
        return self._avg_market_value

    @avg_market_value.setter
    def avg_market_value(self, avg_market_value):
        """Sets the avg_market_value of this CompetitorsSameCars.

        Estimated market value of year make model combination  # noqa: E501

        :param avg_market_value: The avg_market_value of this CompetitorsSameCars.  # noqa: E501
        :type: float
        """

        self._avg_market_value = avg_market_value

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CompetitorsSameCars):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
