# coding: utf-8

"""
    Marketcheck Cars API

    <b>Access the New, Used and Certified cars inventories for all Car Dealers in US.</b> <br/>The data is sourced from online listings by over 44,000 Car dealers in US. At any time, there are about 6.2M searchable listings (about 1.9M unique VINs) for Used & Certified cars and about 6.6M (about 3.9M unique VINs) New Car listings from all over US. We use this API at the back for our website <a href='https://www.marketcheck.com' target='_blank'>www.marketcheck.com</a> and our Android and iOS mobile apps too.<br/><h5> Few useful links : </h5><ul><li>A quick view of the API and the use cases is depicated <a href='https://portals.marketcheck.com/mcapi/' target='_blank'>here</a></li><li>The Postman collection with various usages of the API is shared here https://www.getpostman.com/collections/2752684ff636cdd7bac2</li></ul>  # noqa: E501

    OpenAPI spec version: 1.0.3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from marketcheck_api_sdk.models.dealer import Dealer  # noqa: F401,E501


class DealersResponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'num_found': 'int',
        'dealers': 'list[Dealer]'
    }

    attribute_map = {
        'num_found': 'num_found',
        'dealers': 'dealers'
    }

    def __init__(self, num_found=None, dealers=None):  # noqa: E501
        """DealersResponse - a model defined in Swagger"""  # noqa: E501

        self._num_found = None
        self._dealers = None
        self.discriminator = None

        if num_found is not None:
            self.num_found = num_found
        if dealers is not None:
            self.dealers = dealers

    @property
    def num_found(self):
        """Gets the num_found of this DealersResponse.  # noqa: E501

        number of dealers found  # noqa: E501

        :return: The num_found of this DealersResponse.  # noqa: E501
        :rtype: int
        """
        return self._num_found

    @num_found.setter
    def num_found(self, num_found):
        """Sets the num_found of this DealersResponse.

        number of dealers found  # noqa: E501

        :param num_found: The num_found of this DealersResponse.  # noqa: E501
        :type: int
        """

        self._num_found = num_found

    @property
    def dealers(self):
        """Gets the dealers of this DealersResponse.  # noqa: E501


        :return: The dealers of this DealersResponse.  # noqa: E501
        :rtype: list[Dealer]
        """
        return self._dealers

    @dealers.setter
    def dealers(self, dealers):
        """Sets the dealers of this DealersResponse.


        :param dealers: The dealers of this DealersResponse.  # noqa: E501
        :type: list[Dealer]
        """

        self._dealers = dealers

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, DealersResponse):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
