# coding: utf-8

"""
    Marketcheck Cars API

    <b>Access the New, Used and Certified cars inventories for all Car Dealers in US.</b> <br/>The data is sourced from online listings by over 44,000 Car dealers in US. At any time, there are about 6.2M searchable listings (about 1.9M unique VINs) for Used & Certified cars and about 6.6M (about 3.9M unique VINs) New Car listings from all over US. We use this API at the back for our website <a href='https://www.marketcheck.com' target='_blank'>www.marketcheck.com</a> and our Android and iOS mobile apps too.<br/><h5> Few useful links : </h5><ul><li>A quick view of the API and the use cases is depicated <a href='https://portals.marketcheck.com/mcapi/' target='_blank'>here</a></li><li>The Postman collection with various usages of the API is shared here https://www.getpostman.com/collections/2752684ff636cdd7bac2</li></ul>  # noqa: E501

    OpenAPI spec version: 1.0.3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class FuelEfficiency(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'city_mileage': 'str',
        'highway_mileage': 'str',
        'combined_mileage': 'str',
        'annual_miles': 'float',
        'monthly_fuel_expense': 'float'
    }

    attribute_map = {
        'city_mileage': 'city_mileage',
        'highway_mileage': 'highway_mileage',
        'combined_mileage': 'combined_mileage',
        'annual_miles': 'annual_miles',
        'monthly_fuel_expense': 'monthly_fuel_expense'
    }

    def __init__(self, city_mileage=None, highway_mileage=None, combined_mileage=None, annual_miles=None, monthly_fuel_expense=None):  # noqa: E501
        """FuelEfficiency - a model defined in Swagger"""  # noqa: E501

        self._city_mileage = None
        self._highway_mileage = None
        self._combined_mileage = None
        self._annual_miles = None
        self._monthly_fuel_expense = None
        self.discriminator = None

        if city_mileage is not None:
            self.city_mileage = city_mileage
        if highway_mileage is not None:
            self.highway_mileage = highway_mileage
        if combined_mileage is not None:
            self.combined_mileage = combined_mileage
        if annual_miles is not None:
            self.annual_miles = annual_miles
        if monthly_fuel_expense is not None:
            self.monthly_fuel_expense = monthly_fuel_expense

    @property
    def city_mileage(self):
        """Gets the city_mileage of this FuelEfficiency.  # noqa: E501

        City Mileage in MPG  # noqa: E501

        :return: The city_mileage of this FuelEfficiency.  # noqa: E501
        :rtype: str
        """
        return self._city_mileage

    @city_mileage.setter
    def city_mileage(self, city_mileage):
        """Sets the city_mileage of this FuelEfficiency.

        City Mileage in MPG  # noqa: E501

        :param city_mileage: The city_mileage of this FuelEfficiency.  # noqa: E501
        :type: str
        """

        self._city_mileage = city_mileage

    @property
    def highway_mileage(self):
        """Gets the highway_mileage of this FuelEfficiency.  # noqa: E501

        Highway Mileage in MPG  # noqa: E501

        :return: The highway_mileage of this FuelEfficiency.  # noqa: E501
        :rtype: str
        """
        return self._highway_mileage

    @highway_mileage.setter
    def highway_mileage(self, highway_mileage):
        """Sets the highway_mileage of this FuelEfficiency.

        Highway Mileage in MPG  # noqa: E501

        :param highway_mileage: The highway_mileage of this FuelEfficiency.  # noqa: E501
        :type: str
        """

        self._highway_mileage = highway_mileage

    @property
    def combined_mileage(self):
        """Gets the combined_mileage of this FuelEfficiency.  # noqa: E501

        Combined Mileage  # noqa: E501

        :return: The combined_mileage of this FuelEfficiency.  # noqa: E501
        :rtype: str
        """
        return self._combined_mileage

    @combined_mileage.setter
    def combined_mileage(self, combined_mileage):
        """Sets the combined_mileage of this FuelEfficiency.

        Combined Mileage  # noqa: E501

        :param combined_mileage: The combined_mileage of this FuelEfficiency.  # noqa: E501
        :type: str
        """

        self._combined_mileage = combined_mileage

    @property
    def annual_miles(self):
        """Gets the annual_miles of this FuelEfficiency.  # noqa: E501

        Annual Miles of Car  # noqa: E501

        :return: The annual_miles of this FuelEfficiency.  # noqa: E501
        :rtype: float
        """
        return self._annual_miles

    @annual_miles.setter
    def annual_miles(self, annual_miles):
        """Sets the annual_miles of this FuelEfficiency.

        Annual Miles of Car  # noqa: E501

        :param annual_miles: The annual_miles of this FuelEfficiency.  # noqa: E501
        :type: float
        """

        self._annual_miles = annual_miles

    @property
    def monthly_fuel_expense(self):
        """Gets the monthly_fuel_expense of this FuelEfficiency.  # noqa: E501

        Monthly fuel expense  # noqa: E501

        :return: The monthly_fuel_expense of this FuelEfficiency.  # noqa: E501
        :rtype: float
        """
        return self._monthly_fuel_expense

    @monthly_fuel_expense.setter
    def monthly_fuel_expense(self, monthly_fuel_expense):
        """Sets the monthly_fuel_expense of this FuelEfficiency.

        Monthly fuel expense  # noqa: E501

        :param monthly_fuel_expense: The monthly_fuel_expense of this FuelEfficiency.  # noqa: E501
        :type: float
        """

        self._monthly_fuel_expense = monthly_fuel_expense

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, FuelEfficiency):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
