# coding: utf-8

"""
    Marketcheck Cars API

    <b>Access the New, Used and Certified cars inventories for all Car Dealers in US.</b> <br/>The data is sourced from online listings by over 44,000 Car dealers in US. At any time, there are about 6.2M searchable listings (about 1.9M unique VINs) for Used & Certified cars and about 6.6M (about 3.9M unique VINs) New Car listings from all over US. We use this API at the back for our website <a href='https://www.marketcheck.com' target='_blank'>www.marketcheck.com</a> and our Android and iOS mobile apps too.<br/><h5> Few useful links : </h5><ul><li>A quick view of the API and the use cases is depicated <a href='https://portals.marketcheck.com/mcapi/' target='_blank'>here</a></li><li>The Postman collection with various usages of the API is shared here https://www.getpostman.com/collections/2752684ff636cdd7bac2</li></ul>  # noqa: E501

    OpenAPI spec version: 1.0.3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class ListingLease(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'lease_term': 'int',
        'down_payment': 'float',
        'estimated_monthly_payment': 'float'
    }

    attribute_map = {
        'lease_term': 'lease_term',
        'down_payment': 'down_payment',
        'estimated_monthly_payment': 'estimated_monthly_payment'
    }

    def __init__(self, lease_term=None, down_payment=None, estimated_monthly_payment=None):  # noqa: E501
        """ListingLease - a model defined in Swagger"""  # noqa: E501

        self._lease_term = None
        self._down_payment = None
        self._estimated_monthly_payment = None
        self.discriminator = None

        if lease_term is not None:
            self.lease_term = lease_term
        if down_payment is not None:
            self.down_payment = down_payment
        if estimated_monthly_payment is not None:
            self.estimated_monthly_payment = estimated_monthly_payment

    @property
    def lease_term(self):
        """Gets the lease_term of this ListingLease.  # noqa: E501

        Lease term for this lease offer  # noqa: E501

        :return: The lease_term of this ListingLease.  # noqa: E501
        :rtype: int
        """
        return self._lease_term

    @lease_term.setter
    def lease_term(self, lease_term):
        """Sets the lease_term of this ListingLease.

        Lease term for this lease offer  # noqa: E501

        :param lease_term: The lease_term of this ListingLease.  # noqa: E501
        :type: int
        """

        self._lease_term = lease_term

    @property
    def down_payment(self):
        """Gets the down_payment of this ListingLease.  # noqa: E501

        Down payment for this lease offer  # noqa: E501

        :return: The down_payment of this ListingLease.  # noqa: E501
        :rtype: float
        """
        return self._down_payment

    @down_payment.setter
    def down_payment(self, down_payment):
        """Sets the down_payment of this ListingLease.

        Down payment for this lease offer  # noqa: E501

        :param down_payment: The down_payment of this ListingLease.  # noqa: E501
        :type: float
        """

        self._down_payment = down_payment

    @property
    def estimated_monthly_payment(self):
        """Gets the estimated_monthly_payment of this ListingLease.  # noqa: E501

        estimated monthly payment for this lease offer  # noqa: E501

        :return: The estimated_monthly_payment of this ListingLease.  # noqa: E501
        :rtype: float
        """
        return self._estimated_monthly_payment

    @estimated_monthly_payment.setter
    def estimated_monthly_payment(self, estimated_monthly_payment):
        """Sets the estimated_monthly_payment of this ListingLease.

        estimated monthly payment for this lease offer  # noqa: E501

        :param estimated_monthly_payment: The estimated_monthly_payment of this ListingLease.  # noqa: E501
        :type: float
        """

        self._estimated_monthly_payment = estimated_monthly_payment

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ListingLease):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
