# coding: utf-8

"""
    Marketcheck Cars API

    <b>Access the New, Used and Certified cars inventories for all Car Dealers in US.</b> <br/>The data is sourced from online listings by over 44,000 Car dealers in US. At any time, there are about 6.2M searchable listings (about 1.9M unique VINs) for Used & Certified cars and about 6.6M (about 3.9M unique VINs) New Car listings from all over US. We use this API at the back for our website <a href='https://www.marketcheck.com' target='_blank'>www.marketcheck.com</a> and our Android and iOS mobile apps too.<br/><h5> Few useful links : </h5><ul><li>A quick view of the API and the use cases is depicated <a href='https://portals.marketcheck.com/mcapi/' target='_blank'>here</a></li><li>The Postman collection with various usages of the API is shared here https://www.getpostman.com/collections/2752684ff636cdd7bac2</li></ul>  # noqa: E501

    OpenAPI spec version: 1.0.3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class NestDealer(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'int',
        'name': 'str',
        'website': 'str',
        'street': 'str',
        'city': 'str',
        'state': 'str',
        'country': 'str',
        'zip': 'str',
        'latitude': 'str',
        'longitude': 'str',
        'phone': 'str',
        'seller_email': 'str'
    }

    attribute_map = {
        'id': 'id',
        'name': 'name',
        'website': 'website',
        'street': 'street',
        'city': 'city',
        'state': 'state',
        'country': 'country',
        'zip': 'zip',
        'latitude': 'latitude',
        'longitude': 'longitude',
        'phone': 'phone',
        'seller_email': 'seller_email'
    }

    def __init__(self, id=None, name=None, website=None, street=None, city=None, state=None, country=None, zip=None, latitude=None, longitude=None, phone=None, seller_email=None):  # noqa: E501
        """NestDealer - a model defined in Swagger"""  # noqa: E501

        self._id = None
        self._name = None
        self._website = None
        self._street = None
        self._city = None
        self._state = None
        self._country = None
        self._zip = None
        self._latitude = None
        self._longitude = None
        self._phone = None
        self._seller_email = None
        self.discriminator = None

        if id is not None:
            self.id = id
        if name is not None:
            self.name = name
        if website is not None:
            self.website = website
        if street is not None:
            self.street = street
        if city is not None:
            self.city = city
        if state is not None:
            self.state = state
        if country is not None:
            self.country = country
        if zip is not None:
            self.zip = zip
        if latitude is not None:
            self.latitude = latitude
        if longitude is not None:
            self.longitude = longitude
        if phone is not None:
            self.phone = phone
        if seller_email is not None:
            self.seller_email = seller_email

    @property
    def id(self):
        """Gets the id of this NestDealer.  # noqa: E501

        The unique id associated with the dealer in the Marketcheck database  # noqa: E501

        :return: The id of this NestDealer.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this NestDealer.

        The unique id associated with the dealer in the Marketcheck database  # noqa: E501

        :param id: The id of this NestDealer.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def name(self):
        """Gets the name of this NestDealer.  # noqa: E501

        Name of the dealer  # noqa: E501

        :return: The name of this NestDealer.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this NestDealer.

        Name of the dealer  # noqa: E501

        :param name: The name of this NestDealer.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def website(self):
        """Gets the website of this NestDealer.  # noqa: E501

        Website of the dealer  # noqa: E501

        :return: The website of this NestDealer.  # noqa: E501
        :rtype: str
        """
        return self._website

    @website.setter
    def website(self, website):
        """Sets the website of this NestDealer.

        Website of the dealer  # noqa: E501

        :param website: The website of this NestDealer.  # noqa: E501
        :type: str
        """

        self._website = website

    @property
    def street(self):
        """Gets the street of this NestDealer.  # noqa: E501

        Street of the dealer  # noqa: E501

        :return: The street of this NestDealer.  # noqa: E501
        :rtype: str
        """
        return self._street

    @street.setter
    def street(self, street):
        """Sets the street of this NestDealer.

        Street of the dealer  # noqa: E501

        :param street: The street of this NestDealer.  # noqa: E501
        :type: str
        """

        self._street = street

    @property
    def city(self):
        """Gets the city of this NestDealer.  # noqa: E501

        City of the dealer  # noqa: E501

        :return: The city of this NestDealer.  # noqa: E501
        :rtype: str
        """
        return self._city

    @city.setter
    def city(self, city):
        """Sets the city of this NestDealer.

        City of the dealer  # noqa: E501

        :param city: The city of this NestDealer.  # noqa: E501
        :type: str
        """

        self._city = city

    @property
    def state(self):
        """Gets the state of this NestDealer.  # noqa: E501

        State of the dealer  # noqa: E501

        :return: The state of this NestDealer.  # noqa: E501
        :rtype: str
        """
        return self._state

    @state.setter
    def state(self, state):
        """Sets the state of this NestDealer.

        State of the dealer  # noqa: E501

        :param state: The state of this NestDealer.  # noqa: E501
        :type: str
        """

        self._state = state

    @property
    def country(self):
        """Gets the country of this NestDealer.  # noqa: E501

        country of the dealer  # noqa: E501

        :return: The country of this NestDealer.  # noqa: E501
        :rtype: str
        """
        return self._country

    @country.setter
    def country(self, country):
        """Sets the country of this NestDealer.

        country of the dealer  # noqa: E501

        :param country: The country of this NestDealer.  # noqa: E501
        :type: str
        """

        self._country = country

    @property
    def zip(self):
        """Gets the zip of this NestDealer.  # noqa: E501

        Zip of the dealer  # noqa: E501

        :return: The zip of this NestDealer.  # noqa: E501
        :rtype: str
        """
        return self._zip

    @zip.setter
    def zip(self, zip):
        """Sets the zip of this NestDealer.

        Zip of the dealer  # noqa: E501

        :param zip: The zip of this NestDealer.  # noqa: E501
        :type: str
        """

        self._zip = zip

    @property
    def latitude(self):
        """Gets the latitude of this NestDealer.  # noqa: E501

        Latutide for the dealer location  # noqa: E501

        :return: The latitude of this NestDealer.  # noqa: E501
        :rtype: str
        """
        return self._latitude

    @latitude.setter
    def latitude(self, latitude):
        """Sets the latitude of this NestDealer.

        Latutide for the dealer location  # noqa: E501

        :param latitude: The latitude of this NestDealer.  # noqa: E501
        :type: str
        """

        self._latitude = latitude

    @property
    def longitude(self):
        """Gets the longitude of this NestDealer.  # noqa: E501

        Longitude for the dealer location  # noqa: E501

        :return: The longitude of this NestDealer.  # noqa: E501
        :rtype: str
        """
        return self._longitude

    @longitude.setter
    def longitude(self, longitude):
        """Sets the longitude of this NestDealer.

        Longitude for the dealer location  # noqa: E501

        :param longitude: The longitude of this NestDealer.  # noqa: E501
        :type: str
        """

        self._longitude = longitude

    @property
    def phone(self):
        """Gets the phone of this NestDealer.  # noqa: E501

        Contact no of the dealer  # noqa: E501

        :return: The phone of this NestDealer.  # noqa: E501
        :rtype: str
        """
        return self._phone

    @phone.setter
    def phone(self, phone):
        """Sets the phone of this NestDealer.

        Contact no of the dealer  # noqa: E501

        :param phone: The phone of this NestDealer.  # noqa: E501
        :type: str
        """

        self._phone = phone

    @property
    def seller_email(self):
        """Gets the seller_email of this NestDealer.  # noqa: E501

        Contact email of the dealer  # noqa: E501

        :return: The seller_email of this NestDealer.  # noqa: E501
        :rtype: str
        """
        return self._seller_email

    @seller_email.setter
    def seller_email(self, seller_email):
        """Sets the seller_email of this NestDealer.

        Contact email of the dealer  # noqa: E501

        :param seller_email: The seller_email of this NestDealer.  # noqa: E501
        :type: str
        """

        self._seller_email = seller_email

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, NestDealer):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
