# coding: utf-8

"""
    Marketcheck Cars API

    <b>Access the New, Used and Certified cars inventories for all Car Dealers in US.</b> <br/>The data is sourced from online listings by over 44,000 Car dealers in US. At any time, there are about 6.2M searchable listings (about 1.9M unique VINs) for Used & Certified cars and about 6.6M (about 3.9M unique VINs) New Car listings from all over US. We use this API at the back for our website <a href='https://www.marketcheck.com' target='_blank'>www.marketcheck.com</a> and our Android and iOS mobile apps too.<br/><h5> Few useful links : </h5><ul><li>A quick view of the API and the use cases is depicated <a href='https://portals.marketcheck.com/mcapi/' target='_blank'>here</a></li><li>The Postman collection with various usages of the API is shared here https://www.getpostman.com/collections/2752684ff636cdd7bac2</li></ul>  # noqa: E501

    OpenAPI spec version: 1.0.3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class ReviewComponents(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'user_name': 'str',
        'user_rating': 'float',
        'actual_review': 'str'
    }

    attribute_map = {
        'user_name': 'user_name',
        'user_rating': 'user_rating',
        'actual_review': 'actual_review'
    }

    def __init__(self, user_name=None, user_rating=None, actual_review=None):  # noqa: E501
        """ReviewComponents - a model defined in Swagger"""  # noqa: E501

        self._user_name = None
        self._user_rating = None
        self._actual_review = None
        self.discriminator = None

        if user_name is not None:
            self.user_name = user_name
        if user_rating is not None:
            self.user_rating = user_rating
        if actual_review is not None:
            self.actual_review = actual_review

    @property
    def user_name(self):
        """Gets the user_name of this ReviewComponents.  # noqa: E501

        Name of user who has given review  # noqa: E501

        :return: The user_name of this ReviewComponents.  # noqa: E501
        :rtype: str
        """
        return self._user_name

    @user_name.setter
    def user_name(self, user_name):
        """Sets the user_name of this ReviewComponents.

        Name of user who has given review  # noqa: E501

        :param user_name: The user_name of this ReviewComponents.  # noqa: E501
        :type: str
        """

        self._user_name = user_name

    @property
    def user_rating(self):
        """Gets the user_rating of this ReviewComponents.  # noqa: E501

        rating for dealer given by user ranging from 1-5  # noqa: E501

        :return: The user_rating of this ReviewComponents.  # noqa: E501
        :rtype: float
        """
        return self._user_rating

    @user_rating.setter
    def user_rating(self, user_rating):
        """Sets the user_rating of this ReviewComponents.

        rating for dealer given by user ranging from 1-5  # noqa: E501

        :param user_rating: The user_rating of this ReviewComponents.  # noqa: E501
        :type: float
        """

        self._user_rating = user_rating

    @property
    def actual_review(self):
        """Gets the actual_review of this ReviewComponents.  # noqa: E501

        review of car given by current user  # noqa: E501

        :return: The actual_review of this ReviewComponents.  # noqa: E501
        :rtype: str
        """
        return self._actual_review

    @actual_review.setter
    def actual_review(self, actual_review):
        """Sets the actual_review of this ReviewComponents.

        review of car given by current user  # noqa: E501

        :param actual_review: The actual_review of this ReviewComponents.  # noqa: E501
        :type: str
        """

        self._actual_review = actual_review

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ReviewComponents):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
